#!/usr/bin/env python3
#
# post-update
#
# The post-update git hook for an aberdeen blog repo
#
"""
To use this, copy this file into the 'hooks' directory in your server's git
repository. Also, add a configuration file to tell aberdeen where to send
the generated blog posts.
"""

from sys import argv
import aberdeen as ab

print("===post-update===")
print ("Args:", argv)

for ref_name in argv[1:]:
    branch = ab.call_git(['rev-parse', '--symbolic', '--abbrev-ref', ref_name])

    # with open("$HOME/postupdate.log", 'r+') as log:
    print ("Update pushed to branch %s" % (branch))

    if branch == 'publish':
        pass
