#!/usr/bin/env python3
#
# update
#
# The 'update' git hook for verifying the publish branch
#
"""
To use this, copy this file into the 'hooks' directory in your server's git
repository. Also, add a configuration file to tell aberdeen where to send
the generated blog posts.
"""

import sys

print("===update===")
print ("Args:", sys.argv)

branch, old_commit, new_commit = sys.argv[1:4]

if branch.split('/')[-1] == 'publish':
    import aberdeen
    from markdown import Markdown

    diff_cmd = "diff --name-only %s %s -- *.md" % (old_commit, new_commit)
    changed_filenames = aberdeen.call_git(diff_cmd.split()).strip()

    ls_tree_cmd = 'ls-tree --full-name -r %s' % (new_commit)
    files_changed = [
        {'name': line.split()[3], 'blob': line.split()[2]}
        for line in aberdeen.call_git(ls_tree_cmd).split('\n')[:-1]
        if line.split('\t')[-1] in changed_filenames
    ]
    print ("Changed markdown files in new commit:", files_changed)

    for file in files_changed:
        print ("Testing:", file['name'])
        cat_cmd = "cat-file blob " + file['blob']
        markdown = aberdeen.call_git(cat_cmd.split())
        print (" contents:\n----\n", markdown, "----")
        try:
            aberdeen.generate_from_markdown(markdown)
        except:
            err = ("There was an error generating a post from file '%s'.\n"
                   "The error thrown was: '%s'\n"
                   "The commit was NOT accepted. Please fix the file and push "
                   "the changes again. ") % (filename)
            print(err, file=sys.stderr)
    sys.exit(1)
